// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB0-qH9kRP2NhMYnWmJ3LeltDNEIXJo6k',
    appId: '1:362474958:web:faa34590a423531da3cf9f',
    messagingSenderId: '362474958',
    projectId: 'buddy-ec712',
    authDomain: 'buddy-ec712.firebaseapp.com',
    storageBucket: 'buddy-ec712.firebasestorage.app',
    measurementId: 'G-5QEE1M8E7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYMGiBQK8uLWOEQYY0vNOV0acY0OE_CXs',
    appId: '1:362474958:android:2c6c63802908a0f3a3cf9f',
    messagingSenderId: '362474958',
    projectId: 'buddy-ec712',
    storageBucket: 'buddy-ec712.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBopIJ4Yoyuok5p0E77940ofewW6QW1DGo',
    appId: '1:362474958:ios:f18a12ed6d5b65dea3cf9f',
    messagingSenderId: '362474958',
    projectId: 'buddy-ec712',
    storageBucket: 'buddy-ec712.firebasestorage.app',
    iosBundleId: 'com.example.flutterchatapp',
  );
}
